### ISSUE TITLE
Should the Panel component have a border-radius on desktop.

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/big-design#1031]
**Concise question or problem statement**

The [Design document](https://design.bigcommerce.com/components/panels), and many areas of the admin (product options, product filters, product import/export, transactional emails) use a panel that has a border radius on tablet devices and larger.

Whereas Product Categories and Channel manager do not have a border-radius.

The Panel in this library never has a border-radius applied.

This seems like it perhaps used to be the case once upon a time looking at [this test](https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Panel/__snapshots__/spec.tsx.snap#L8). 

My nerdy question is: should the Panel component have a border-radius on tablet devices and larger?

![Screenshot 2022-10-27 at 13 58 03](https://user-images.githubusercontent.com/553566/198293183-7a757c3a-921b-438d-9b99-b19b608fdaab.png)
![Screenshot 2022-10-27 at 13 58 18](https://user-images.githubusercontent.com/553566/198293191-47eb33c2-758b-4f75-80f0-cbe06982fa76.png)
![Screenshot 2022-10-27 at 13 58 45](https://user-images.githubusercontent.com/553566/198293204-a563ffe6-1d09-4ef0-b00a-0ef9bce519cb.png)
![Screenshot 2022-10-27 at 13 58 54](https://user-images.githubusercontent.com/553566/198293219-71f1468b-410a-4ea6-b230-07023af8d5e6.png)
![Screenshot 2022-10-27 at 13 58 58](https://user-images.githubusercontent.com/553566/198293231-5d1a9318-700a-408c-a9bb-bddecb4f95b6.png)
![Screenshot 2022-10-27 at 13 59 07](https://user-images.githubusercontent.com/553566/198293236-9cd368ea-39fa-4699-a661-fa029a0c8bd1.png)
![Screenshot 2022-10-27 at 13 59 10](https://user-images.githubusercontent.com/553566/198293242-12618834-e96a-436c-a304-919d47738635.png)
![Screenshot 2022-10-27 at 14 09 28](https://user-images.githubusercontent.com/553566/198293333-c2517158-cc9f-4ac9-a942-579f58187396.png)
![Screenshot 2022-10-27 at 14 09 35](https://user-images.githubusercontent.com/553566/198293340-c1031df9-260d-4a4a-b1fa-9c18c96664e8.png)

**Comment by chanceaclark** [comment]
🤦‍♂️ Good catch @bobbyshaw!

Looks like that was a regression from https://github.com/bigcommerce/big-design/pull/962. Went ahead and added a fix: #1032

**Comment by bobbyshaw** [comment]
I'm glad it wasn't me losing my mind. 

Thanks for the quick response & swifter fix ✌️
