### ISSUE TITLE
Add `description/subheader` prop to `Panel`.

### ISSUE THREAD

**Issue by jorgemoya** [bigcommerce/big-design#1109]
**Is your feature request related to a problem? Please describe.**

Sometimes a `Panel` requires an additional description to provide more context to the `Panel`. The issue of the `Panel` component is that the `H2` title of the `Panel` has a large bottom margin that prevents adding additional text as a`description/subheader` without a large space in between. Not the prettiest.

<img width="927" alt="Screenshot 2023-01-24 at 4 50 28 PM" src="https://user-images.githubusercontent.com/196129/214438644-b3d4522a-74ea-4467-844f-0215ce5bc153.png">

**Describe the solution, feature, or improvement you'd like**

Allow a `description/subheader` prop that, when available, sets the correct spacing (designs tbd).

<img width="901" alt="Screenshot 2023-01-24 at 4 54 14 PM" src="https://user-images.githubusercontent.com/196129/214439247-dcb3a204-b33f-4e07-a13a-003f9975c6a2.png">

**Describe alternatives you've considered**
Modify the `h2` margin?

**Additional context**
I've seen this pattern multiple times and feel like this would be a great addition to the `Panel` component.

What do we think?

**Comment by eugene-polev** [comment]
Good call-out. We definitely should consider the description below the header as part of the header. It means that the margin should be added after the description. See [the example in Figma](https://www.figma.com/file/duwtpbP2tnLLQQmAkwtrNC/BigDesign-Lib?node-id=12894%3A43473&t=P1XEhklSrwznDfNO-1)

**Comment by jorgemoya** [comment]
> Good call-out. We definitely should consider the description below the header as part of the header. It means that the margin should be added after the description. See [the example in Figma](https://www.figma.com/file/duwtpbP2tnLLQQmAkwtrNC/BigDesign-Lib?node-id=12894%3A43473&t=P1XEhklSrwznDfNO-1)

Thanks for the examples @eugene-polev! Should be easy to implement.
