### ISSUE TITLE
how to implement an application made with nexjs in my store within the bigcommerce

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/big-design#1130]
how to implement an application made with nexjs in my store within the bigcommerce?

**Comment by chanceaclark** [comment]
Hey @bernardojru! Thanks for reaching out here! We actually have a NextJS starter repo + BigDesign that you can check out:
- [Starter Repo](https://github.com/bigcommerce/sample-app-nodejs)
- Here's the [developer documentation](https://developer.bigcommerce.com/docs/ZG9jOjE4MjIyODI5-quick-start-deploy-to-heroku-install-flow) to quick start that repo

If you have any issues setting that up, reach out in the GitHub issues over in that repo. I'm going to close this as it's not fully relevant to our component library.
