### ISSUE TITLE
Adding full label internationalization support

### ISSUE THREAD

**Issue by davelinke** [bigcommerce/big-design#1194]
**Is your feature request related to a problem? Please describe.**
Within the component library there are a few components that have got labels or attributes that are written in english and cannot be changed to other languages.

Here's a list of such components and possible solutions:

[Pagination Component](https://developer.bigcommerce.com/big-design/pagination)
Needs the word "of" to be passed as a property/attribute to be able to internationalize.

[Stateful table with Search](https://developer.bigcommerce.com/big-design/statefulTable?implementation=search)
Needs the word "Search"  to be passed as a property/attribute to be able to internationalize, or needs to provide the instance of the search input as property to do it directly on the child component.

[Stateful Table with pagination](https://developer.bigcommerce.com/big-design/statefulTable?implementation=pagination-and-selection)
The assumption is that this one gets fixed by fixing the pager component.

[Stateful Table with Drag and drop](https://developer.bigcommerce.com/big-design/statefulTable?implementation=drag-and-drop)
Needs a property/attribute to be added to provide an alt/title property on the dragging icon to show a proper message in any language

[Table with pagination](https://developer.bigcommerce.com/big-design/table?implementation=pagination)
The assumption is that this one gets fixed by fixing the pager component.

[Table - Sortable](https://developer.bigcommerce.com/big-design/table?implementation=sortable)
Needs the labels "Ascending Order" and "Descending Order" that are provided as "alt/title" tags for the icons to be passed as a property/attribute to be able to internationalize.

[Table with Drag and Drop](https://developer.bigcommerce.com/big-design/table?implementation=drag-and-drop)
Same as "stateful table" with drag and drop.

[Worksheet - Expandable Rows](https://developer.bigcommerce.com/big-design/worksheet?implementation=expandable-rows)
Needs the phrase "toggle row expanded" to be passed as a property/attribute to be able to internationalize.

[ButtonGroup](https://developer.bigcommerce.com/big-design/button-group)
Needs the word "more" that is provided as an "alt/title" tag for the ellipsis icon to be passed as a property/attribute to be able to internationalize.

[Counter](https://developer.bigcommerce.com/big-design/counter)
Needs the labels "Decrease Count" and "Increase Count" that are provided as "alt/title" tags for the icons to be passed as a property/attribute to be able to internationalize.

[Input, Select, MultiSelect, Textarea, DatePicker, TimePicker](https://developer.bigcommerce.com/big-design/form?implementation=input-types&props=form-fieldset)
The Form inputs need  the word "Optional" to be passed as a property/attribute to be able to internationalize.

[Search](https://developer.bigcommerce.com/big-design/search)
Needs the word "Search"  to be passed as a property/attribute to be able to internationalize.

[InlineMessage](https://developer.bigcommerce.com/big-design/inline-message?implementation=onclose)
Needs the word "close" that is provided as an "alt/title" tag for the closing icon to be passed as a property/attribute to be able to internationalize.

[Message](https://developer.bigcommerce.com/big-design/message)
Needs the word "close" that is provided as an "alt/title" tag for the closing icon to be passed as a property/attribute to be able to internationalize.

Making it possible to pass those labels to the components would allow the library to be fully compatible with other languages other than english.

**Describe the solution, feature, or improvement you'd like**
My suggestion would be adding additional properties to such components to be able to pass a string in the desired language.

**Comment by chanceaclark** [comment]
Fixed via `v0.37.0`
