### ISSUE TITLE
Keep MultiSelect dropdown always open

### ISSUE THREAD

**Issue by cassio-fernandes-ct** [bigcommerce/big-design#1305]
**Is your feature request related to a problem? Please describe.**
When using the MultiSelect component, it seems the functionality regarding wether the dropdown box is open or not is inconsistent. Sometime you'll click on a couple of options and it'll select all of them without closing the dropdown, but sometimes you click and the dropdown closes immediately, prompting the user to open the dropdown again, and if they're looking to select many options this gets frustrating very fast.

**Describe the solution, feature, or improvement you'd like**
I think it'd be best if it was clearer when the dropdown should be open and when it should be closed. A prop such as "isOpen" or making it close only when a click off of the dropdown area should solve the issue.

**Describe alternatives you've considered**
Looking through the code I'm assuming it has something to do with the `handleStateReducer` at `dist/es/components/MultiSelect/MultiSelect.js` setting the isOpen to false. If we could force it always open onFocus and always closed out of focus of the input, I believe that'd be one way to solve the issue.
![image](https://github.com/bigcommerce/big-design/assets/96853224/f350a3c2-d738-4de4-87b4-8ac98d3edb53)

**Additional context**
Of course I don't have in depth knowledge on how the package is built, but if any additional information is required, please let me know.

Thanks in advance!

**Comment by chanceaclark** [comment]
Hey @cassio-fernandes-ct thanks for opening this issue! We've definitely chatted about this issue before, and I think we do need to solve the issue where it closes when selecting options. My only callout is on this:

>If we could force it always open onFocus and always closed out of focus of the input, I believe that'd be one way to solve the issue.

We need to conform to these accessibility requirements regarding a combobox https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/ That being said, I think that the dropdown should not open when being focused on the input.

**Comment by chanceaclark** [comment]
This should be fixed in `v0.38.2`.
