### ISSUE TITLE
Modal incorrectly focuses any input it contains

### ISSUE THREAD

**Issue by leeBigCommerce** [bigcommerce/big-design#1316]
**Describe the bug**

Opening a modal immediately sets focus on the first input found within it.

**To Reproduce**
1. Create a `Modal` containing an input
2. Open that `Modal`
3. See that the input is already focussed

**Expected behavior**
That the modal itself is focussed

There appears to be a [test attempting to protect the expect behavior](https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Modal/spec.tsx#L162), but I think there might be a mismatch between how JSDom and Chrome handle the focusing - hence the test passing, but the bug appearing in the browser.

**Screenshots**

https://github.com/bigcommerce/big-design/assets/56807262/73eab86c-1841-4267-97fd-7aed79c192d9

**Comment by chanceaclark** [comment]
Hey @leeBigCommerce I think this is actually intended based on the [W3 guide for Dialogs/Modals](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/#:~:text=Closes%20the%20dialog.-,Note,-When%20a%20dialog), however they do outline some caveats to what should be focused depending on the content in the modal. They have some recommendations there if you need the initial focus to not be on the first focusable element.

Regarding that test, I believe it is in regards to the focus not changing when the modal rerenders which doesn't apply to this functionality from what I see 🤔

**Comment by leeBigCommerce** [comment]
Cheers @chanceaclark, looks like I should be able to use `tabindex` to try and pick something better.

It was this bit of the test which made me think we wanted the behaviour to be "focus the modal itself":

https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Modal/spec.tsx#L175-L185

`await waitFor(() => expect(document.activeElement).toBe(queryByRole('dialog')));` - this coming purely after a rendering of the open modal
