### ISSUE TITLE
Better way to make responsive props

### ISSUE THREAD

**Issue by chanceaclark** [bigcommerce/big-design#132]
**Is your feature request related to a problem? Please describe.**
During development of #131 and #113 it was a bit tedious to make each prop responsive. Having to the do this for each prop was cumbersome:
```tsx
type SingleProp = type;
type ResponsiveProp = Responsive<SingleProp>;
type Prop = SingleProp | ResponsiveProp;
```

**Describe the solution, feature, or improvement you'd like**
We need to think of a way to make props responsive without all the copy pasta.

**Comment by amckemie** [comment]
JIRA ticket: CHP-6014.
