### ISSUE TITLE
Declarative theme props 

### ISSUE THREAD

**Issue by chanceaclark** [bigcommerce/big-design#190]
**Describe the solution, feature, or improvement you'd like**
Currently `theme` can be passed into components imperatively. We need to be more declarative that `theme` can be passed into individual components. For example our Button component is correct:
```tsx
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, MarginProps {
  actionType?: 'normal' | 'destructive';
  iconLeft?: React.ReactChild;
  iconOnly?: React.ReactChild;
  iconRight?: React.ReactChild;
  isLoading?: boolean;
  theme?: ThemeInterface;
  variant?: 'primary' | 'secondary' | 'subtle';
}
```
We'll need to go through other components and declare that `theme` can be passed in.

**Comment by amckemie** [comment]
Jira for remaining components: CHP-6164

**Comment by deini** [comment]
Closing this since we are discouraging `theme` props.
