### ISSUE TITLE
Feature Req: Display treatment for "external" link

### ISSUE THREAD

**Issue by bookernath** [bigcommerce/big-design#236]
**Is your feature request related to a problem? Please describe.**
I can't clearly communicate to users the difference between internal "navigation" links and external links with the native capabilities of BigDesign.

**Describe the solution, feature, or improvement you'd like**
Sometimes, you need to create links that will open in a new tab, to link to an external resource like documentation. It's nice to hint to users that this will happen with some sort of display treatment like this:

![image](https://user-images.githubusercontent.com/8922457/68391685-c9dbc200-012d-11ea-83ae-0ac2cb905086.png)

This sort of visual language makes the user less surprised when we open a new tab instead of navigate.

It seems like a reasonable extension to the `<Link>` component API. Perhaps it can be an explicitly set flag, or perhaps it can implicitly react to use of `target="_blank"` and so on.

**Describe alternatives you've considered**
Styling the link by hand.

**Comment by deini** [comment]
Fixed by #243
