### ISSUE TITLE
Feature request: More easily add a <Form> into a <Modal> using the native modal buttons

### ISSUE THREAD

**Issue by bookernath** [bigcommerce/big-design#253]
**Is your feature request related to a problem? Please describe.**
It's a manual process to use a modal as a form at the moment, if you wish to use the native `actions` to create nicely styled buttons.

**Describe the solution, feature, or improvement you'd like**
A new `<ModalForm>` component, or a cleaner way of using the buttons on a `<Modal>` to submit a form within the modal.

For example:

```
      <Modal
        header="Create a new thing"
        actions={[
        { text: 'Cancel', onClick: () => setIsOpen(false) },
        { text: 'Create', type: "submit", action: "submit" },
        ]}
      >
        <Form onSubmit={handleSubmit}>
        //form elements
        </Form>
      </Modal>
```

Or perhaps:

```
      <ModalForm
        header="Create a new thing"
        actions={[
        { text: 'Cancel', onClick: () => setIsOpen(false) },
        { text: 'Create', type: "submit", action: "submit" },
        ]}
      >
        //form elements
      </Modal>
```

**Describe alternatives you've considered**
Using the `onClick()` event and refs to submit the form in a targeted way.

**Additional context**
It seems like the action buttons on modals naturally lend themselves to form-like actions, so making this easier might reduce the time it takes to build a common workflow.

**Comment by chanceaclark** [comment]
HTML5 introduced the `form` attribute on buttons:
https://stackoverflow.com/questions/7020659/submit-form-using-a-button-outside-the-form-tag#answer-12567605

Have we tried something like that?

**Comment by deini** [comment]
@chanceaclark suggestion implementation example https://codesandbox.io/s/gracious-edison-k4qgc

Note: This doesn't work on IE

**Comment by valterfatia** [comment]
Moving the issue to internal JIRA…
