### ISSUE TITLE
Feature Request: Date/Time picker component

### ISSUE THREAD

**Issue by bookernath** [bigcommerce/big-design#255]
**Is your feature request related to a problem? Please describe.**
For scheduling use cases, it's needed to allow a user to select a particular date and/or time that something should happen. There's nothing perfect for this use case with the native input components in BigDesign right now.

**Describe the solution, feature, or improvement you'd like**
A Date and/or Time input component for forms, such as:

https://www.npmjs.com/package/react-moment-datepicker
https://www.npmjs.com/package/react-datetime-picker

... but styled within BigDesign.

**Comment by valterfatia** [comment]
Good thing that we already have a design and working component in promotions then :)
Animesh is on holidays but he should be back next week… meanwhile here's the design https://www.figma.com/file/WR9G5WX678v9pRaG9UYlMw2r/Date-Picker?node-id=0%3A1

cc @animesh1987 have we made progress on submitting the DatePicker into BigDesign?

**Comment by animesh1987** [comment]
Sorry for late reply. Haven't committed the component yet. Might get around to doing it in the last sprint of this year.

**Comment by amckemie** [comment]
@animesh1987 Any updates on the date / time picker? A partner requested this as one of their top 5 requests for BigDesign

**Comment by animesh1987** [comment]
Hi @amckemie I have started working on getting datepicker in big-design. Aiming to get the code merged sometime next week.
