### ISSUE TITLE
Modals containing no focusable elements throws focus-trap error

### ISSUE THREAD

**Issue by chanceaclark** [bigcommerce/big-design#298]
**Describe the bug**
Let's say you have a modal implementation like so:
```tsx
<Modal isOpen={true}>Hello</Modal>
```
Opening a modal with no `actions` elements or focusable elements inside the modal throws an error:
`Error: Your focus-trap needs to have at least one focusable element`.

Application will then crash.

**To Reproduce**
See above.

**Expected behavior**
Modal should be able to open regardless if there are/not focusable elements inside.

Regression bug from #252.

**Comment by deini** [comment]
https://github.com/bigcommerce/big-design/pull/311
