### ISSUE TITLE
Select does not accept FormControlLabel type

### ISSUE THREAD

**Issue by bc-williamkwon** [bigcommerce/big-design#355]
**Is your feature request related to a problem? Please describe.**
Would like there to be a FormControlLabelType so that one may add a label with an icon over the input ... it would be useful for adding a tooltip over that icon so that a user may have more information about what the specific input is to be used for

**Comment by chanceaclark** [comment]
We should definitely add this to have uniformity with the rest of the form control components. 

Also to add onto this issue:
- Ensure `label` uniformity for `MultiSelect` with other form controls.
- Ensure `description` uniformity for `Select` & `MultiSelect` with other form controls.
- Add `description` prop to both `Select` and `MultiSelect` prop tables. Currently, it's a valid prop to pass into the component, but documentation doesn't reflect it.
