### ISSUE TITLE
After build for the production mode in react, bigdesign style are not appearing.

### ISSUE THREAD

**Issue by NaveenaTsMaximizer** [bigcommerce/big-design#370]
### **Before build:**

![image](https://user-images.githubusercontent.com/28294118/79261258-31502780-7ead-11ea-9329-39ee41ec120d.png)

### **After Build:**

![image](https://user-images.githubusercontent.com/28294118/79261364-593f8b00-7ead-11ea-9d6f-e8804cdc77cc.png)

**Comment by chanceaclark** [comment]
Hey @NaveenaTsMaximizer, I'm wondering if you could provide some more info on your build process.
