### ISSUE TITLE
Select.onOptionChange works unpredictably

### ISSUE THREAD

**Issue by Borales** [bigcommerce/big-design#396]
**Describe the bug**
`Select.onOptionChange` prop does not work as expected.

**To Reproduce**
1. https://codesandbox.io/s/lingering-pond-5szw9?file=/src/App.js
2. Select any value from the Select component - **Nothing happens**

**Expected behavior**
Changing the value should trigger the `onOptionChange` event.

**Additional context**
Downgrading to 0.18.0 fixes the problem (can be validated via the left sidebar - changing the version of the package)

**Comment by Borales** [comment]
On my local - it works differently, it triggers an infinite loop when storing the selected value in the state, not sure why I can't reproduce it on codesandbox.

**Comment by deini** [comment]
Fix is now available in `0.19.2`, thanks for opening this issue @Borales! 🙇

**Comment by Borales** [comment]
thanks for fixing it so fast! 👍
