### ISSUE TITLE
Rendering Button as Router.Link

### ISSUE THREAD

**Issue by Borales** [bigcommerce/big-design#397]
**Describe the bug**

```js
import { Link } from 'react-router-dom';
import { Button } from '@bigcommerce/big-design';

export default () => (
  <Button
    as={Link}  
    type="button"
    variant="subtle"
    to={{ pathname: '/next-page', search: location.search }} 
  >    
Go next
  </Button>
)
```

In order to ensure client-side navigation - I need to use `Link` component provided by `react-router` package. The code above gives me the following HTML output:

```html
<a
  class="styled__StyledButton-..." 
  role="button" 
  tabindex="0" 
  type="button" 
  variant="subtle" 
  actiontype="normal" 
  theme="[object Object]" 
  href="/next-page">
  <span class="styled__ContentWrapper-sc-3yq204-1 cUnSLq">Go Next</span>
</a>
```

You can see some attributes being passed to the `<a>` tag without processing. Some of them are not valid attributes for `<a>` tag, therefore I get warnings in the console (even though from the design perspective - it looks as expected).

**Expected behavior**
All non-valid HTML attributes should be filtered out.

**Screenshots**

<img width="887" alt="Screenshot 2020-05-07 at 22 09 33" src="https://user-images.githubusercontent.com/1118933/81340067-813a9c80-90af-11ea-9c0a-48504abfc734.png">

I might be misusing the component and it should be used in another way - I'd like to ask for your advice.

**Comment by chanceaclark** [comment]
@Borales I'm wondering if you can achieve the same functionality like this:
```tsx
<Link to={{ pathname: '/next-page', search: location.search }} style={{ textDecoration: "none" }}>
    <Button type="button" variant="subtle">
        Go next
    </Button>
</Link>
```

**Comment by Borales** [comment]
🤦‍♂️ I can.. that was an obvious solution, yet I decided to go with hacks  😄 it works

thank you @chanceaclark

**Comment by chanceaclark** [comment]
Just a forewarning, the snippet above has some accessibility quirkiness to it. You'll probably want to add a `tabIndex={0}` and `aria-label="Go next"` to the `Link` while applying an `aria-hidden` to the `Button`. That may not be the best, but I would play around with it.
