### ISSUE TITLE
Progress indicator bar should have rounded corners

### ISSUE THREAD

**Issue by valterfatia** [bigcommerce/big-design#404]
Considering the bar only has 4px in height the corners will be fully rounded on both ends.

**Comment by chanceaclark** [comment]
@valterfatia what is the border-radius for the rounded ends?

**Comment by valterfatia** [comment]
4px! Our standard measure

**Comment by bc-Shuvy** [comment]
Just confirming we reviewed the design for this, decision seems to be it's too small for the radius to appear right - current design stands.

**Comment by chanceaclark** [comment]
@valterfatia @bc-Shuvy can we close this issue then?
