### ISSUE TITLE
Incorrect sizes on checkboxes and radio buttons

### ISSUE THREAD

**Issue by valterfatia** [bigcommerce/big-design#407]
I noticed some inconsistencies on sizing of these 2 components, so I'm raising this issue with the correct specs:
- Both components/graphics should have a bounding box of 24px/2.4rem
- Radio button size should be 22px, with 1px margin
- Checkboxes should be 20px, with 2px margin

**Comment by chanceaclark** [comment]
Just want to get some clarification, is it 24px or 2.4rem?

Our base font-size is 16px so `2.4 x = 16 = 38.4px`.

**Comment by valterfatia** [comment]
Ups got my design system confused :)

24px is the right measure.

**Comment by valterfatia** [comment]
BIGDESIGN-215
