### ISSUE TITLE
Popup menus should be 4px in distance from the triggering element

### ISSUE THREAD

**Issue by valterfatia** [bigcommerce/big-design#412]
At the moment we have a mix of 4/8px on these. Ideally we should use 4px consistently

**Comment by jorgemoya** [comment]
It's actually set to `10px`, this is what `4px` looks like:

<img width="484" alt="Screen Shot 2020-07-27 at 3 20 31 PM" src="https://user-images.githubusercontent.com/196129/88588187-c28e7880-d01c-11ea-8fd3-0b728a597bda.png">

@valterfatia looks good?

**Comment by valterfatia** [comment]
4px looks good! I think it's fine for tooltips to stay different!
