### ISSUE TITLE
Feature Request:  Step Component

### ISSUE THREAD

**Issue by arsh-cedcoss** [bigcommerce/big-design#420]
Need a Step Component to show on which step the user  is in Registration or Sign Up.

Reference Image:
![Screenshot (5)](https://user-images.githubusercontent.com/53248675/87706811-c240e280-c7bd-11ea-8fc0-c3c771907b3b.png)

**Comment by chanceaclark** [comment]
👋 Hey again @arsh-cedcoss, we currently have a component like this planned in our backlog. It's just the matter of prioritizing it.

**Comment by arsh-cedcoss** [comment]
Hey @chanceaclark, I hope you guys will bring this in upcoming updates.

**Comment by chanceaclark** [comment]
Closed with #503
