### ISSUE TITLE
Feature Request: Draggable Rows on Stateful Table

### ISSUE THREAD

**Issue by bc-sumi** [bigcommerce/big-design#426]
**Is your feature request related to a problem? Please describe.**
The current UI for tables allows for draggable rows but the Stateful Table does not support this feature.

**Describe the solution, feature, or improvement you'd like**
I would like to have draggable rows part of Stateful Table like the ones shown here. 
https://www.figma.com/file/Rj63WSTZQc2H4XI9Oi3r5o/MSF-design-(LATEST)?node-id=10702%3A0

<img width="868" alt="Screen Shot 2020-07-29 at 9 35 54 PM" src="https://user-images.githubusercontent.com/58491357/88881162-88bb9e80-d1e3-11ea-8e87-d925b9dcc280.png">

**Comment by chanceaclark** [comment]
Hey @bc-sumi, we currently have this feature request on our backlog! I'll send you the ticket offline, PR's are always welcomed though! Otherwise, we'll need to prioritize this appropriately.

**Comment by animesh1987** [comment]
We have an draggable rows implementation in one of the microapps, but it's not using Stateful table and we used [React DnD](https://github.com/atlassian/react-beautiful-dnd) library. Possibly can be used to get started.
