### ISSUE TITLE
Description for `selectable` in `Tree` seems off

### ISSUE THREAD

**Issue by icatalina** [bigcommerce/big-design#431]
**Describe the bug**
Description for the `selectable` prop in the `Tree` component seems off.

**To Reproduce**
https://developer.bigcommerce.com/big-design/tree

**Expected behavior**
A description of what the `selectable` prop means

**Screenshots**
<img width="888" alt="image" src="https://user-images.githubusercontent.com/4542735/89478007-0da14c00-d7d2-11ea-91f3-56a1e7bb4346.png">

**Comment by chanceaclark** [comment]
Oops. PR's are always welcome @icatalina ;)

**Comment by chanceaclark** [comment]
Fixed in #481
