### ISSUE TITLE
Select options icons color/ add an icon on the select input

### ISSUE THREAD

**Issue by bc-sumi** [bigcommerce/big-design#432]
**Is your feature request related to a problem? Please describe.**
I would like to change the icons color on the select options to match the designs. I would also like to add a search icon on the actual search input.

**Describe the solution, feature, or improvement you'd like**
Select can add the ability to add colors to the select options and add an icon on the search input. 

**How it currently looks:** 
<img width="1680" alt="Screen Shot 2020-08-07 at 1 40 07 PM" src="https://user-images.githubusercontent.com/58491357/89691856-e83e3c00-d8be-11ea-9725-30e00d6b2199.png">

**How the design file looks:** 
<img width="712" alt="Screen Shot 2020-08-07 at 3 03 03 PM" src="https://user-images.githubusercontent.com/58491357/89691930-191e7100-d8bf-11ea-9864-785193b02359.png">

**Comment by valterfatia** [comment]
Merged.
