### ISSUE TITLE
Selects: Empty dropdown item remains after selection

### ISSUE THREAD

**Issue by chibicode** [bigcommerce/big-design#459]
**Describe the bug**

On the Select component, after selecting an item, an empty dropdown item remains.

![Kapture 2020-10-13 at 22 39 31](https://user-images.githubusercontent.com/992008/95949020-a8a43c80-0da6-11eb-8729-3552d8aac16a.gif)

**To Reproduce**
1. Go to https://developer.bigcommerce.com/big-design/select
2. Click on the topmost country select box
3. Click on any other country name
4. See that an empty popup item remains

**Expected behavior**

The empty popup item should not appear.

**Desktop (please complete the following information, if applicable):**
 - OS: [e.g. iOS] macOS 10.15.7
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 86

**Comment by chibicode** [comment]
Related: https://github.com/bigcommerce/big-design/issues/460

**Comment by jorgemoya** [comment]
Thanks for the report, will take a look.

**Comment by jorgemoya** [comment]
Hey @chibicode I can't seem to be able to reproduce this. I'm running almost identical specs as you. Could there be some unexpected changes in the example code that may make this trigger?

**Comment by chibicode** [comment]
@jorgemoya This might be specific to the Chrome version I’m using. It has this error on:

- Chrome 86.0.4240.75
- Chrome 86.0.4240.80

I tried it on Chrome Canary (88.0.4292.0) and it has a similar error - the size of the box that appears is a bit smaller:

![Kapture 2020-10-14 at 09 41 43](https://user-images.githubusercontent.com/992008/96019662-b2a75900-0e01-11eb-9417-514920e2c4af.gif)
 
I tried it in Safari and Firefox and couldn’t reproduce it.

**Comment by chibicode** [comment]
@jorgemoya Confirmed that this is fixed on the latest version. Thanks!
