### ISSUE TITLE
Selects: Cannot re-select by clicking inside the box

### ISSUE THREAD

**Issue by chibicode** [bigcommerce/big-design#460]
**Describe the bug**

On the select component, after selecting an item, you cannot trigger the dropdown by clicking inside the box. The only way to show the dropdown is to click on the triangle. This is inconsistent because initially, you can trigger the dropdown by clicking inside the box.

![Kapture 2020-10-13 at 23 03 53](https://user-images.githubusercontent.com/992008/95950032-b35fd100-0da8-11eb-8502-745c53d5b5c8.gif)

**To Reproduce**
1. Go to https://developer.bigcommerce.com/big-design/select
2. Click on the topmost country select box
3. Click on any other country name
4. Click on inside the box

**Expected behavior**

Expected: Dropdown opens again
Actual: Nothing happens

**Desktop (please complete the following information, if applicable):**
- OS: [e.g. iOS] macOS 10.15.7
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 86

**Comment by chibicode** [comment]
Related: https://github.com/bigcommerce/big-design/issues/459

**Comment by chibicode** [comment]
Maybe `onFocus` doesn’t fire when it’s already focused?
https://github.com/bigcommerce/big-design/blob/7f1fb23b245d4b54a5294c754a9efda23fbad728/packages/big-design/src/components/Select/Select.tsx#L253

**Comment by jorgemoya** [comment]
> Maybe `onFocus` doesn’t fire when it’s already focused?
> https://github.com/bigcommerce/big-design/blob/7f1fb23b245d4b54a5294c754a9efda23fbad728/packages/big-design/src/components/Select/Select.tsx#L253

Yeah, I think it is along those lines. Will take a look.

**Comment by chibicode** [comment]
@jorgemoya confirmed this one is fixed. thank you!
