### ISSUE TITLE
Auto-focused tree component item cause a scroll of long pages

### ISSUE THREAD

**Issue by BC-YIvashchenko** [bigcommerce/big-design#469]
**Describe the bug**
During the initialization of a `Tree` component, there is some node that is going to be focused.
When the node is focused it causes window scroll so users are unable to see the loaded page from the very top.
 
**To Reproduce**
1. Go to CP new `Category manager`
2. Click on `Create category`
3. Notice the page is scrolled down to a categories tree

**Expected behavior**
The `Tree` component should not affect the window offset.

**Desktop (please complete the following information, if applicable):**
 - OS: macOs
 - Browser: chrome
 - Version: 86.0.4240.111

**Comment by chanceaclark** [comment]
Fixed in #481
