### ISSUE TITLE
Enable optional badge prop on panels

### ISSUE THREAD

**Issue by rtalvarez** [bigcommerce/big-design#476]
**Is your feature request related to a problem? Please describe.**
No problems right now, just surfacing a suggestion to the panel props

**Describe the solution, feature, or improvement you'd like**
I'm not sure if this is too specific, might warrant more discussion or might not even apply, but thought it might be a good idea to surface it anyway.

We usually have panels that look like this:
<img width="848" alt="Screen Shot 2020-12-07 at 1 44 35 PM" src="https://user-images.githubusercontent.com/6025510/101397514-66711600-3892-11eb-888a-3389d07d4b56.png">

When this is the case, we cannot use the `action` and `header` helpers on the panel props since there would be no way for the badge to be correctly aligned. Maybe it would be helpful to provide a new prop that allows for a badge to be added, for example `badge?: BadgeProps & { text: string }` 

**Describe alternatives you've considered**
Manually adding header, action and badge

**Comment by jorgemoya** [comment]
If this is a recurring pattern, I don't see why we shouldn't build it. Do we need to bring this with design?

**Comment by valterfatia** [comment]
Tracked on BIGDESIGN-211
