### ISSUE TITLE
Several multiselects in a form

### ISSUE THREAD

**Issue by alnine** [bigcommerce/big-design#487]
I'm using Bigdesing library in my project, and I need to have several multiselects in one form. I have one handler to handle result of changes on multiselects. And here I have problem because onOptionChange returns just value and option and I know nothing which one of multiselects called the handler. I tried to use onChange event, but it don't work at all. Maybe I do something wrong. 

For clear I will try to describe what I do and why. 
I have form where I don't know how much multiselect will be. This is must be dynamic and depends to how much product categories I receive. So I have list of categories and I have list of some options. With help multiselect I need to connect category with selected options from list. Every category can have one or more options. Thats why I have one handler to handle change on multiselect. And I can't make different handlers for each multiselect. I need to know which one of multiselects called the handler and connect it with selected options.

I use React/Typescript in my project.

Can anybody help me with this problem?

Thanks for any answer!

**Comment by deini** [comment]
👋 Can you tell us a little bit more about why you can't use different handlers?

If you can give us an example in a [CodeSandbox](https://codesandbox.io/s/github/bigcommerce/big-design/tree/%40bigcommerce/examples%400.13.0/packages/examples) it will be easier for us to help.

**Comment by alnine** [comment]
Hi, @deini! Thanks for your attention) 

Yes, of course I try to describe it better.
I have dynamic list of categories and permanent list of options. Each category can have different set of options from the list. User can choose that with help of multiselect. So I need to have one multiselect for each category but every multiselect will have the same list of options. User selects options for every categories, and at the finish I need to send data that will have info about categories and its options. Its well work when I have one multiselect - user makes choose, onOptionChange return me value and option, and I can handle it in single handler. But if I have two multiselect I need have one more handler for it. But this handler will do the same procces that previous. Thats way working well while I know how much categories I have and for every of them I can write similiar handlers. But I don't know how much categories I will have. It can be one, but can be 50 even. And I need to have handlers for each of them. But why, if thats handlers will do the same work. The only difference is category. I could write one handler that gets multiselect id and its selected options, and thats handler will handle infinite of different multiselects. 

I can prepare example code if its need, but I need more time. Maybe you have understood me and my idea/problem )
Thanks you!)

**Comment by deini** [comment]
Yeah if you can prepare an example that would be great. 🙇 

You can try doing something like:
```jsx
onOptionChange={(value, option) => {
  genericHandler('some-id', value, option);
})
```

**Comment by alnine** [comment]
@deini thanks, I just thought about it too, so I am going to try this solution on Monday, the solution may fit

**Comment by alnine** [comment]
@deini Hi! 

Thanks for your tip, I tried it and that fits for me. 
However, I think it would be better if some multiselect identifier was in props of optionChange. Because commonly when I use several similar fields in forms I try use universal handler that need to know just value and field id/name, so I can use many fields and only one handler that know where it should write a value by id/name. When I don't have identifier I have to use addition handler that will pass id instead to call main handler at once. It don't mean that you should to pass all there are to props of optionChange, identifier will be enough to understand what is one of multiselects called a handler. 
Maybe I am wrong and watch in wrong angle, sorry for that. But thanks you for fast answer and suitable tip 👍
