### ISSUE TITLE
Select component highlight first option

### ISSUE THREAD

**Issue by bc-sumi** [bigcommerce/big-design#494]
**Is your feature request related to a problem? Please describe.**
 It would reduce time for users to be able to type and hit and enter the word they are selecting from the Select component.

**Describe the solution, feature, or improvement you'd like**
When you start typing, the first option should be auto selected/highlighted. Currently you have to click on the option you want to Select.

**Describe alternatives you've considered**
I've also considered when the input word matches a word from the Select component list and if a user hits enter then that should automatically select that option.

**Comment by jorgemoya** [comment]
Hey @bc-sumi. Thanks for the suggestion. I believe this is doable but I would first like to bring this up with the design team. If I remember correctly the design guidelines showcased the current behavior today. I will make sure to bring it up in the next meet.

**Comment by valterfatia** [comment]
Tracked on BIGDESIG-224
