### ISSUE TITLE
Add responsive display props for Table Columns 

### ISSUE THREAD

**Issue by kwang30** [bigcommerce/big-design#496]
**Is your feature request related to a problem? Please describe.**
It would be nice to have props to control the responsive  display of the table columns in the Table/StatefulTable Components. Currently have added styling to control this (mobile, tablet, desktop responsive display), but adding props into big-design would be nice.  

**Describe the solution, feature, or improvement you'd like**
Table/StatefulTable Components props could be able to control the display of the responsive table column display.

**Describe alternatives you've considered**
Currently have added styling around the Table Component to control the responsive display of the colums - 

```
export const StyledTable = styled.div`
    tr td:nth-child(3) {
        display: none;
    }
    tr th:nth-child(3) {
        display: none;
    }
    word-break: break-word;
    ${({ theme }) => theme.breakpoints.tablet} {
        tr td:nth-child(3) {
            display: table-cell;
        }
        tr th:nth-child(3) {
            display: table-cell;
        }
    }
`;
``` 
**Additional context**
CC: @chanceaclark

**Comment by valterfatia** [comment]
Tracked on BIGDESIG-225
