### ISSUE TITLE
Issue with TableFigure / Table overflow when selecting number of items to display.

### ISSUE THREAD

**Issue by pedelman** [bigcommerce/big-design#502]
**Describe the bug**
When we have no items in the Table, when clicking the number of items dropdown, the layout seems to have some glitches causing the header to shift unexpectedly. This only seems to be an issue when the table is wrapped in the TableFigure component.

**To Reproduce**
1. Go to https://codesandbox.io/s/dazzling-gareth-ljsb9?file=/src/index.tsx
2. Click the number of items dropdown
3. Notice the display issues, there seems to be some issues with overflow. The table header seems to shift when clicking.

**Expected behavior**
Expect the dropdown to float above the table with no shift in layout / overflow positioning.

To repro, see: https://codesandbox.io/s/dazzling-gareth-ljsb9?file=/src/index.tsx

**Screenshots**
<img width="730" alt="Screen Shot 2021-02-01 at 4 05 58 PM" src="https://user-images.githubusercontent.com/955777/106533626-6747b200-64a7-11eb-965f-09dca176de47.png">

**Desktop (please complete the following information, if applicable):**
 - Device: Macbook Pro 2019
 - OS: macOS Catalina 10.15.7
 - Browser: Chrome
 - Version: Version 88.0.4324.96 (Official Build) (x86_64)

**Additional context**
N/A

**Comment by valterfatia** [comment]
Tracked on BIGDESIGN-226.

**Comment by jorgemoya** [comment]
This issue should be resolved with changes in https://github.com/bigcommerce/big-design/pull/505
