### ISSUE TITLE
Change terminology of mixins folder/files

### ISSUE THREAD

**Issue by jorgemoya** [bigcommerce/big-design#511]
**Is your feature request related to a problem? Please describe.**
In #510 it became apparent we are not thinking about mixins as reusable, so the terminology mixin might not be the correct one.

**Describe the solution, feature, or improvement you'd like**
Change terminology. To what? Not sure yet, want to open a discussion about it.

**Additional context**
This all started when on #510 instead of adding extra types to the current `display` mixin I decided to duplicate the code to keep the specific use case closer to its usage.

**Comment by chanceaclark** [comment]
I don't have a strong opinion on this, but as a suggested rename, I'm throwing `helpers` into the ring 🤷
