### ISSUE TITLE
Popover example code not working

### ISSUE THREAD

**Issue by jp06** [bigcommerce/big-design#519]
**Describe the bug**
Popover example code does not work on either the playground or a local environment.

**To Reproduce**
1. Setup global styles with the `GlobalStyles` component in the root component.
2. Use the Popover example code on the documentation/playground after importing the required components and `useState` hook. 

**Expected behavior**
I expected something to pop up like the [image here](https://github.com/bigcommerce/big-design/pull/441) but nothing really pops up.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.128

**Comment by chanceaclark** [comment]
Thanks @jp06 for bringing this to our attention, we'll take a look at resolving this.
