### ISSUE TITLE
MultiSelect component with 'required' prop never passes validation 

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/big-design#524]
**Describe the bug**
When using the `MultiSelect` component with `required` attribute, the HTML validation always triggers to say there's no selection even when there is. 

**To Reproduce**

Create MultiSelect component with required prop inside a form

```
const App = () => {
  const [value, setValue] = useState(['1']);

  return (
    <Form>
      <FormGroup>
        <MultiSelect
            label="Select Multiple"
            filterable
            options={[
              { value: "1", content: "Option 1" },
              { value: "2", content: "Option 2" },
              { value: "3", content: "Option 3" }
            ]}
            value={value}
            required={true}
            onOptionsChange={(val) => setValue(val)}
          />
      </FormGroup>
      <Button>Save</Button>
    </Form>
 );
}

```

View codesandbox example: https://codesandbox.io/s/priceless-gould-focz8?file=/src/index.tsx

**Expected behavior**

When a MultiSelect with the required prop has one or more options selected, it should pass validation. 

**Screenshots**

![Screenshot 2021-04-22 at 10 01 32](https://user-images.githubusercontent.com/553566/115687189-d8ce2880-a351-11eb-84f8-df80cfbd7536.png)

**Potential Diagnosis**

It _seems_ like this is because there is always an empty HTML input within the multi-select which always has the required flag without taking into account whether there have already been some selections.  

![Screenshot 2021-04-22 at 10 06 41](https://user-images.githubusercontent.com/553566/115688085-b8eb3480-a352-11eb-847c-47efc5cf4a06.png)

From digging into the code, I'm not sure of the best way to go about solving this. Perhaps it would be to force set the required prop to false on the `input` if there are chips?  

https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Input/Input.tsx#L164

**Desktop:**
 - OS: Mac OS 11.2.3
 - Browser: Chrome 89

**Comment by jorgemoya** [comment]
I looked into this yesterday. There's some approaches we can look into:

1. Easiest for sure is to fix it like @bobbyshaw suggested. Pretty quick change.
2. I started looking into other libraries to see how they handled this approach. By looking at [this example](https://www.telerik.com/kendo-react-ui/components/dropdowns/multiselect/forms/) my guess is that they are handling some `element.validity` logic in javascript. Looks clean but it would definitely require some rethinking about the form logic.
3. Last approach was to look into having a hidden input that stringifies the chosen values, but I have no experience with this solution (how can we tie both inputs together to accept/reject them?). I would need to dive deeper into this and look for example uses,  not even sure if it fits our use case.

So it really depends on how much time we want to invest on this and if we don't feel like going with the first approach.

**Comment by amckemie** [comment]
Bug Ticket created: https://jira.bigcommerce.com/browse/CHP-7068

**Comment by yoavmatchulsky** [comment]
Hey, any update on this? :pray: :pray: :pray:

**Comment by jorgemoya** [comment]
@yoavmatchulsky Haven't had the chance to work on it, unfortunately. Will need to coordinate to see when I can look at the proposed solutions and work with the best one.
