### ISSUE TITLE
Feature Request: Support disabling autocomplete for Search component

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/big-design#580]
**Is your feature request related to a problem? Please describe.**

I'm consuming the new Search component (thank you) into a search autocomplete box. I would like to have the option of disabling native browser autocomplete to avoid them masking the search results. 

![Screenshot 2021-08-24 at 11 50 22](https://user-images.githubusercontent.com/553566/130605066-b4ebd6ab-b2b8-43e1-b49f-9885bedae92a.png)
![Screenshot 2021-08-24 at 11 50 35](https://user-images.githubusercontent.com/553566/130605069-437d6af9-2ab4-4e03-82d0-dd0d4fe3c9be.png)

**Describe the solution, feature, or improvement you'd like**

Support passing autocomplete prop similar to #540.

**Comment by chanceaclark** [comment]
https://github.com/bigcommerce/big-design/pull/678 cc. @bobbyshaw

**Comment by bobbyshaw** [comment]
Brilliant thanks @chanceaclark
