### ISSUE TITLE
MultiSelect able to remove items while disabled

### ISSUE THREAD

**Issue by Spawbreaker** [bigcommerce/big-design#587]
**Describe the bug**
The MultiSelect component, when passed the `disabled` prop, still allows users to remove an item from the list. The `Delete` button is still enabled. 

**To Reproduce**
1. Have a MultiSelect with items in it and the `disabled` prop.
2. Click on the `X` button in one of the items to remove it from the list.
3. The item is deleted from the list.

**Expected behavior**
The MultiSelect component, when disabled, does not allow the user to remove an item from the list.

**Screenshots**
![multiselect-bug](https://user-images.githubusercontent.com/37517471/133123454-316e5d07-368f-407a-ae63-b73748ba8bc4.gif)

**Desktop (please complete the following information, if applicable):**
 - OS: MacOS Big Sur 11.4
 - Browser: Chrome
 - Version: Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by jorgemoya** [comment]
Thanks for the report, I will look into this.
