### ISSUE TITLE
Make the FormGroup grid use repeat(x, 1fr) on fullWidth Form component

### ISSUE THREAD

**Issue by Casdak7** [bigcommerce/big-design#660]
It would look a lot nicer if in a fullWidth Form component the FormGroup with multiple inputs actually took up the whole space as well, equally divided.

**Describe the solution, feature, or improvement you'd like**
Either the FormGroup occupy the whole width by default or bring an option to make that the case.

**Describe alternatives you've considered**
I haven't considered any alternative solutions at the moment.

**Additional context**
None.

**Comment by chanceaclark** [comment]
Hey @Casdak7, thanks for the request. This has actually been something we need to tackle as I found a need for it with forms inside modals. Could you perhaps state your use-case though?

**Comment by Casdak7** [comment]
Hey @chanceaclark, that's exactly my use case, a form inside a modal! :smile:
