### ISSUE TITLE
'wrap-reversed' type in flex-wrap is misspelled, should be 'wrap-reverse'

### ISSUE THREAD

**Issue by clopezh** [bigcommerce/big-design#661]
**Describe the bug**
flex-wrap property has a type https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Flex/types.ts#L30 **wrap-reversed** but the correct value is **wrap-reverse**

**To Reproduce**
1. Try to use flexWrap in a Flex component
2. See the unexpected behavior in browser and if you check the inspector you will see the warning:
![image](https://user-images.githubusercontent.com/35146660/145614268-089ec7cb-b37d-4335-80a8-a6d300e9c839.png)

**Expected behavior**
**wrap-reverse** is the correct property according to flex rules.

**Comment by chanceaclark** [comment]
Good catch @clopezh! Definite something to fix!

**Comment by bc-prestonhuth** [comment]
Was this issue ever addressed?
