### ISSUE TITLE
PillTabs does not support items changing

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/big-design#664]
**Describe the bug**
I was trying to use the PillTabs component to filter a table. The items prop is populated through an external call (e.g. fetch order statuses that can then be used within the PillTabs.

When the items array changes length an array access error occurs: "Cannot read properties of undefined (reading 'ref')"

**To Reproduce**
See example at https://codesandbox.io/s/bigcommerce-react-pilltabs-djef3?file=/src/index.tsx

1. Use PillTabs component 
2. Change length of items array provided to PillsTab, e.g. with useEffect hook
4. See error at https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/PillTabs/PillTabs.tsx#L108

**Expected behavior**
Can dynamically change the items without error.

**Screenshots**
![Screenshot 2022-01-13 at 20 45 26](https://user-images.githubusercontent.com/553566/149406671-4d320a43-1515-4b9a-8675-c02406519aa6.png)

 - OS: MacOS 11.6
 - Browser Chrome
 - Version 97

**Additional information**

It seems that [`pillsState` is initiated](https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/PillTabs/PillTabs.tsx#L26) but then not updated when items change .

**Comment by rtalvarez** [comment]
Thanks for the report! I'll look into it

**Comment by rtalvarez** [comment]
Please try using the `0.30.3-alpha.1` version and see if it works!

**Comment by bobbyshaw** [comment]
@rtalvarez That works. Thanks!
