### ISSUE TITLE
ButtonGroup hovers the first destructive button even if disabled

### ISSUE THREAD

**Issue by samufort** [bigcommerce/big-design#676]
**Describe the bug**
Hi,

I have a button group with two destructive buttons hidden under the ellipsis. In some use cases, these buttons are both disabled. When this happens and the user opens the ellipsis, the first button hovers even if it's disabled.

**To Reproduce**
1. Create a button group with two disabled destructive buttons
2. Click on the ellipsis
3. See error

**Expected behavior**
No hover on the first item

**Screenshots**
![2022-01-17 10 53 20](https://user-images.githubusercontent.com/16794649/149802379-0bda7e19-61b6-4cf6-90e4-f2146a0b7f3b.gif)

**Additional context**

**Comment by chanceaclark** [comment]
Hey @samufort, thanks for opening up this issue. This definitely seems like bug so I'll mark it as such.
