### ISSUE TITLE
Table component problems with responsive on smaller screen sizes

### ISSUE THREAD

**Issue by Casdak7** [bigcommerce/big-design#697]
There are problems with the table component on smaller screens. For me, anywhere below a 474px width doesn't resize the table. To me, this happens with the table inside and outside a <Box> wrapper component.

**Comment by chanceaclark** [comment]
Hey @Casdak7, have you tried to use the `TableFigure` element wrapped around the `Table`? It should provide a overflow wrapper for scrolling.

Example,
```jsx
<TableFigure>
  <Table {...props} />
</TableFigure>
```

**Comment by cassio-fernandes-ct** [comment]
This works well with the content that is inside the table, thank you!

But some content stays appearing behind the table on some screen sizes:

![image](https://user-images.githubusercontent.com/96853224/160484747-535be3c6-25fe-493f-a98d-79afba53a890.png)

Or even smaller:
![image](https://user-images.githubusercontent.com/96853224/160484879-d4fe08d0-32ed-4d49-8dd6-63236f01012e.png)

Any thoughts?

**Comment by chanceaclark** [comment]
@cassio-fernandes-ct would you mind shooting over a CodeSandbox example so we could look a little further into your use-case?

**Comment by MariaJose** [comment]
Hey @cassio-fernandes-ct,  tried to reproduce the issue, but I don't see the bug, is there something I should be missing? I'll close this issue, if you still seeing the issue, could you please re-open it and  provide a code example so we can help? Thanks!!

https://user-images.githubusercontent.com/39739180/186973217-6fcc79fb-3746-411c-aa9d-e7ad685578fe.mp4
