### ISSUE TITLE
Modal Component - Typescript children prop not allowed

### ISSUE THREAD

**Issue by bc-micah** [bigcommerce/big-design#843]
**Describe the bug**
Children prop not allowed in typescript for the `Modal` component.

**To Reproduce**
Code sandbox: https://codesandbox.io/s/modal-type-issue-371zcm
1. Setup typescript create react app project
2. Install big-design v0.31.0
3. Use example code from BigDesign docs for `Modal`

**Expected behavior**
No type error for children

**Screenshots**

<img width="1692" alt="Screen Shot 2022-05-25 at 12 16 03 PM" src="https://user-images.githubusercontent.com/95306190/170337661-b4e43d13-6ec0-4a7c-9fc6-8037590cc82c.png">
 help explain your problem.

**Comment by chanceaclark** [comment]
Hey @bc-micah, are you using React v18+?

**Comment by bc-micah** [comment]
Ah okay - I didn't realize that the `children` prop was part of `React.FC`

Sounds like defining the `children` as a prop would be necessary on BigDesign, is there a blocker to adding that type to the ModalProps so that the typings are compatible with React 18?

I resorted to `const Modal: React.FC<ModalProps & { children?: React.ReactNode }> = modal;` to fix it locally.

**Comment by chanceaclark** [comment]
If all you need is the `children` types, just downgrade to v17. If you need some of React's v18 features, then yes you _can_ use v18 along with the `children?: React.ReactNode;` type, but again, I don't recommend using React v18 at this time.

**Comment by MariaJose** [comment]
I'll close this issue, seems this issue can be fix either locally or using React v17
