### ISSUE TITLE
Modal gets a scrollbar while MultiSelect's dropdown is open

### ISSUE THREAD

**Issue by Spawbreaker** [bigcommerce/big-design#862]
**Describe the bug**
The Modal component's height grows while the MultiSelect component's dropdown is active, allowing the user to scroll down when they shouldn't be able to.

I haven't tested it with a Select or a Dropdown component, but it could have the same behavior with them.

**Update**
We found another case where this bug may be related. Adding a second gif and new instructions on how to reproduce:

**To Reproduce**
Steps to reproduce the behavior with a Modal:
1. Have a MultiSelect in a Form.
2. Click on the MultiSelect to get the dropdown to appear.
3. Scroll down in the modal.
4. See the error.
Steps to reproduce the behavior with a Dropdown:
1. Have a table inside a TableFigure.  An element in the table should be a button that causes a Dropdown to appear. The dropdown should have 4-5 options. 
2. Click on the Dropdown. 
3. The TableFigure should be scrolled down and now the TableFigure has a scrollbar.

**Expected behavior**
Modal: The modal should not grow while the MultiSelect's dropdown is active. 
TableFigure: The dropdown should be outside the TableFigure and not cause the TableFigure to grow while it is active.

**Screenshots**
Gif of the bug happening in a modal
![modal-scroll-bug](https://user-images.githubusercontent.com/37517471/172901495-a88c99de-2e85-458e-b999-bb45842e26cb.gif)
Gif of the bug happening in a tablefigure
![table-scroll-bug](https://user-images.githubusercontent.com/37517471/173138468-f3a6c0db-7f87-4f48-8a9d-f17ebaf71cc2.gif)

**Desktop (please complete the following information, if applicable):**
 - OS: macOs 12.2.1
 - Browser: Tested on Chrome and Firefox
 - Version: macOs 12.2.1, Chrome Version 102.0.5005.61 (Official Build) (x86_64), Firefox Version 100.00 (64 bits)

**Comment by chanceaclark** [comment]
Hey @Spawbreaker what version of BigDesign are you using?

**Comment by Spawbreaker** [comment]
I followed up on this today since I had some extra time. I could not replicate it in codesandbox, and in fact, I figured out that remaking the component from scratch fixed the issue. 

I'm not sure exactly what causes this, but I believe that having parts of the Form's body in their own files makes it act weirdly. 

We could mark this as closed if you want!

**Comment by chanceaclark** [comment]
Thanks @Spawbreaker for getting back to us! I'll go ahead and close this!
